### ISSUE TITLE
Error when command entered

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/admin-command#1]
I am getting when I enter `wp admin` after package is installed.

`Couldn't get a file descriptor referring to the console`

Do I need to setup browser or something?

**Comment by danielbachhuber** [comment]
Which operating system are you running?

**Comment by ernilambar** [comment]
OS: `Ubuntu 16.04 LTS`
`uname -a` output `Linux hp-laptop 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by danielbachhuber** [comment]
Ah. I think `open` only works on Mac.

[It appears](http://unix.stackexchange.com/questions/253376/open-command-to-open-a-file-in-an-application) we could use `xdg-open` on Linux. Can you try that out?

**Comment by ernilambar** [comment]
Yes, it works.
