### ISSUE TITLE
`wp admin` does not support Windows

### ISSUE THREAD

**Issue by dgrfdsgn** [wp-cli/admin-command#15]
Windows 10, WP CLI 

`wp admin --info
'xdg-open' is not recognized as an internal or external command,
operable program or batch file.`

 So what's going wrong, how can i get the wp admin command to run? btw, im running WP-CLI 2.0.1 on win10 from powershell. Any help would be greatly appreciated.

[Stackexchange brought me here](https://wordpress.stackexchange.com/questions/318167/xdg-open-is-not-recognized-by-wp-cli-admin-command?noredirect=1#comment470228_318167)

**Comment by schlessera** [comment]
Indeed, as stated on StackExchange, Windows is not yet supported by this command.

I'm open to accepting a pull request to add Windows support, I am not able to test this myself, though.

**Comment by schlessera** [comment]
A quick search seems to confirm that it should just be a matter of using `start` on Windows.

**Comment by dgrfdsgn** [comment]
Im able to test if u want?

**Comment by schlessera** [comment]
@dgrfdsgn Yes, that would be great. I'll look into doing a PR myself later this week.

**Comment by dgrfdsgn** [comment]
@schlessera Is this the commit you want me to test or?

**Comment by dgrfdsgn** [comment]
confirmed after manual install, this now opens a cmd / PS in the WordPress directory, but nothing else.
start is working now, but no browser opened. @schlessera @kingkero

**Comment by dgrfdsgn** [comment]
@schlessera @kingkero Example, im in ~/wp_1/ and perform wp admin, the powershell is opened in ~/wp_1/ although the title says http://localhost/wp_1/wp-admin/ and you're supposed to see a browser open

**Comment by schlessera** [comment]
@dgrfdsgn Thanks for testing and the feedback! I'll look further into this.

**Comment by kingkero** [comment]
Just got my hands on a Win10. Tried the following in default cmd

- `start "example.com"`, opens a new cmd with the URL as title (as dgrdsgn mentioned)
- `start 'example.com'`, gives an error
- `start example.com`, opens the user's default browser.

So the URL needs not be quoted. However, [`escapeshellarg()` will add double-quotes to strings.](https://secure.php.net/manual/en/function.escapeshellarg.php#74815). What do you think is the best way to move forwared here, @schlessera ?

**Comment by schlessera** [comment]
@kingkero From what I can see in the [documentation](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start) and read in [tips on StackExchange](https://superuser.com/questions/36728/can-i-launch-urls-from-command-line-in-windows#comment36859_36730), it seems that `start` assumes the quoted string to be a title when it cannot directly see that it is a URL (i.e., it is missing a protocol).

I would try the following to see whether that works reliably:
```
$exec = 'start ""';
```

**Comment by kingkero** [comment]
`start "" ""https://www.google.com"` worked on my machine, let me rewrite my code. Having problems updating my fork - would it be a shame if I just deleted it with the PR and create a new one?

**Comment by schlessera** [comment]
You need to pull latest changes from upstream master and merge them into your fork.

**Comment by schlessera** [comment]
In case you do not manage to merge upstream master and update your PR and need to create a new one, I recommend create the PR from a branch in your fork instead of from `master`. This way, you can maintain one branch per PR you submit, which makes it very easy to update the PRs if you need to do that (just push to the corresponding branch).

**Comment by schlessera** [comment]
@dgrfdsgn Can you confirm that https://github.com/wp-cli/admin-command/pull/18 now works as expected for you?

**Comment by dgrfdsgn** [comment]
@schlessera @kingkero  Trying, but but `wp package install` doenst seem to finish, hangs on `updateing dependencies`
Steps i followed: delete admin-command from `./wp-cli/packages` 
`wp package install git@github.com:wp-cli/admin-command.git` -- no succes
`git clone https://github.com/wp-cli/admin-command.git` -- worked
`git clone https://github.com/kingkero/admin-command.git` --worked
run `wp admin` in a WP directory, and i get 3 errors:
`PHP Warning: require(###\.wp-cli\packages\vendor\composer/../wp-cli/admin-command/command.php): 
failed to open stream: No such file or directory in ###\.wp-cli\packages\vendor\composer\autoload_real.php on line 66`

Edit: removed my local dir names, ### = something like c:/username/
Checked and there isn't a file called command.php, although there is admin-command.php.
tried renaming that, didnt work.

Installing by composer never finished, so im starting to think i have a problem with that aswell.. Any pointers?

**Comment by dgrfdsgn** [comment]
@schlessera at the last step composers hangs at `composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)` think i might have a new problem with composer. Getting closer, thanks for the help!

**Comment by dgrfdsgn** [comment]
Gonna give it some time @schlessera perhaps i was too quick to judge, ran composer install -vvv:
`composer install -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file C:\###\AppData\Local\Temp\opeB818.tmp: valid
Executing command (D:\tmp\admin-command): git branch --no-color --no-abbrev -v
Executing command (D:\tmp\admin-command): git rev-list master..windows-compatibility
Failed to initialize global composer: Composer could not find the config file: C:/###/AppData/Roaming/Composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.7.3 (2018-11-01 10:05:06) with PHP 5.6.31 on Windows NT / 10.0
Loading composer repositories with package information
Downloading https://repo.packagist.org/packages.json
Writing C:/###/AppData/Local/Composer/repo/https---repo.packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading C:/###/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2013.json from cacheReading C:/###/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2014.json from cache
Reading C:/###/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2015.json from cacheReading C:/###/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2016.json from cache
Reading C:/###/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2017.json from cacheDownloading http://repo.packagist.org/p/provider-2018-01%24fe1f131df382b93afaaa49966ed697e85bdb47b4ece0f970a449c9bdd54fe435.json`

**Comment by dgrfdsgn** [comment]
So that was a big one, finished from what i can tell, and as instructed ran `vendor/bin/wp` but results in same errors as [my previous comment](https://github.com/wp-cli/admin-command/issues/15#issuecomment-438958447) @schlessera im stupped. Any clue what might fix this require error?

**Comment by schlessera** [comment]
@dgrfdsgn Try the following to get rid of the error:
```
wp package uninstall wp-cli/admin-command --skip-packages
```

**Comment by dgrfdsgn** [comment]
Succes! Happy to inform you running `vendor/bin/wp admin --path='some/wp/install/path'` opened my browser and redirects me to login.php. Much WP, Such CLI. 

Thanks a million for support u guys rock! 
@kingkero @schlessera

Gonna be patient and wait untill its merged into master :)

**Comment by schlessera** [comment]
Fixed via #18

**Comment by dgrfdsgn** [comment]
@schlessera So im getting the same error after installing and or updating the package.. i ran, wp package update Using Composer to update packages... Updating dependencies Resolving dependencies through SAT Looking at all rules. Dependency resolution completed in 0.389 seconds Analyzed 6740 packages to resolve dependencies Analyzed 486363 rules to resolve dependencies Package operations: 0 installs, 0 updates, 0 removals Generating autoload files Success: Packages updated. PS> wp admin --path='d:/d/sites/wp__1' 'xdg-open' is not recognized as an internal or external command, operable program or batch file. Is there something im missing?

**Comment by dgrfdsgn** [comment]
Looks like ive got dev-master, after uninstall / install `wp package-list` -> wp-cli/admin-command: dev-master | none

**Comment by schlessera** [comment]
@dgrfdsgn That package was actually not submitted to packagist yet. I did so now. You can add it in the correct version with the following command:
```
wp package install "wp-cli/admin-command:^2"
```

**Comment by Lovor01** [comment]
There is no admin command in my version of WP-CLI (2.5.0 on Win10). I suppose mentioned solution here is still not merged to main branch?
