### ISSUE TITLE
wp admin command hangs when the browser is not already running

### ISSUE THREAD

**Issue by tricarte** [wp-cli/admin-command#29]
As noted in passthru's documentation:

> If a program is started with this function, in order for it to continue running in the background, the output of the program must be redirected to a file or another output stream. Failing to do so will cause PHP to hang until the execution of the program ends.

This hanging issue happens only when the browser is not already running and sometimes can be annoying because if I blindly hit CTRL+C in the shell, I lose all my browser session that is started with "wp admin".

I tried this code, it solves the issue but I'm not %100 sure this is the correct way.
`passthru( $exec . ' ' . escapeshellarg( admin_url() ) . ' > /dev/null 2>&1' );`

**Edit**: OK I totally forgot there are other OSes in this world such as Windows, Doors, Chimneys...

**Comment by danielbachhuber** [comment]
@tricarte Does this issue still reproduce for you?

If I call `wp admin` on my Mac with all browsers closed, Firefox opens as expected.

**Comment by tricarte** [comment]
Sorry for the confusion in the issue.

Firefox was opening as usual. The problem was when I quit Firefox, `wp admin` command did not drop to the command prompt. But I tested just now and it quits properly.
