### ISSUE TITLE
Generate sign on URL 

### ISSUE THREAD

**Issue by clearhost-cmd** [wp-cli/admin-command#38]
It would be good if we could specify a flag for --output etc to generate the link in terminal, so that, that link could be sent to another person to login with.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @clearhost-cmd !

Here's a plugin that does exactly what you're describing: https://wordpress.org/plugins/one-time-login/

Notably, it has to be activated as a plugin, because the URL-handling code needs to run for a web request (which WP-CLI does not).
